### PR TITLE
Justified "Getting Started" and info columns

### PR DESCRIPTION
**Pull request by J3RN**
This was brought up by @egladman. Wanted to get some feedback.

### CODE REVIEW

**Comment by J3RN** [comment]
For reference, this currently looks like this:
screen shot 2015-03-25 at 4 12 17 pm

**Comment by J3RN** [comment]
@egladman @tiranno Thoughts on this?

**Comment by egladman** [comment]
Looks good. One thing that I do is make title text/icons slightly darker, by decreasing the rgb alpha channel by ~10%. YMMV

**Comment by J3RN** [comment]
@egladman Well, this pull request is just about justifying the text. If we were to make it darker, we'd do that separately.

**Comment by egladman** [comment]
:+1:

**Pull request merged**
