### PR TITLE
About page

### LINKED ISSUE #45: About Us Page
Hey @J3RN do we want a more in depth write up about who we are.

For example we could talk about how we were the ruby group and moved to be the CWDG etc.

### PR DESCRIPTION
**Pull request by J3RN**
Closes #45

### CODE REVIEW

**Comment by J3RN** [comment]
Alright, J3RN's shitty design sense says this is ready to ship. Any objections?

**Comment by tarebyte** [comment]
out of curiosity can I see a screen shot of what this looks like?

**Comment by J3RN** [comment]
These are all the relevant sections.
screen shot 2015-03-05 at 7 38 46 pm
screen shot 2015-03-05 at 7 38 51 pm

**Comment by tarebyte** [comment]
Thanks!

**Comment by J3RN** [comment]
Updated screenshot with less creepy image
screen shot 2015-03-08 at 4 18 42 pm

**Comment by J3RN** [comment]
I'm gonna go ahead and merge this.

**Pull request merged**
