### PR TITLE
Convert to static site using Middleman

### PR DESCRIPTION
**Pull request by J3RN**
Conversion to a static site, for a whole host of reasons. These include deployment complexity and server costs.

### CODE REVIEW

**Comment by 3ygun** [comment]
#DontLetYourDreamsBeDreams #JUSTDOIT :tada:

**Comment by J3RN** [comment]
Fixes #113

**Comment by J3RN** [comment]
Alright, I actually think this is finished. Feedback welcome.

Also, I've been debating leaving this repo as-is, and uploading this rewrite to CWDG/cwdg.github.io instead, since that's where it will have to wind up eventually. The alternative is merging this PR, the deleting the cwdg.github.io repository, and renaming this repo cwdg.github.io.

**Comment by 3ygun** [comment]
Question regarding you plan: What are the current 110 commits on CWDG/cwdg.github.io about? Are they merges of this repo's finalized code for deployment? If those 110 commits show "nothing" I would advise the merge this PR > delete current cwdg.github.io > rename

**Comment by J3RN** [comment]
@3ygun Actually there was a real site there, before this one was created. The code still lives on in the "Archive" branch.

I'm leaning towards just moving this rewrite to that repo, and adding it as a single commit. That way the history of both sites is maintained for posterity (whether posterity wants it or not).

**Comment by J3RN** [comment]
Since I'm the *outgoing* president, I'd like to hear what @JohnSimerlink thinks about this.

**Comment by 3ygun** [comment]
@JohnSimerlink I endorse @J3RN single commit approach (don't delete CWDG's historic and beautiful history :D )

We wouldn't want this to be mistaken as a C# or Java web-apps club within a few commits ;)

**Comment by J3RN** [comment]
In lieu of dissenting opinions, I'm going to go ahead and do the single commit onto the CWDG/cwdg.github.io repo, and update DNS.

**Comment by J3RN** [comment]
The new site is live at http://cwdg.github.io. I will update the DNS to reflect that as our new site, if people like it.

**Comment by J3RN** [comment]
The new site has been accepted. Closing this PR and deprecating the repo.

**Pull request closed without merging**
